import namespace from 'helpers/namespace';

export default namespace({
  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,
  SET_PROFILE_SUCCESS: null,
  SET_PROFILE_ERROR: null,
  START_GET_PROFILE: null,
  FINISH_GET_PROFILE: null,

  CREATE_PROFILE_REQUEST: null,
  CREATE_PROFILE_SUCCESS: null,
  CREATE_PROFILE_FAILURE: null,
  START_CREATE_PROFILE: null,
  FINISH_CREATE_PROFILE: null,

  DELETE_PROFILE_REQUEST: null,
  DELETE_PROFILE_SUCCESS: null,
  DELETE_PROFILE_FAILURE: null,
  START_DELETE_PROFILE: null,
  FINISH_DELETE_PROFILE: null,

  CONFIRM_ACTIVATION_REQUEST: null,
  CONFIRM_ACTIVATION_SUCCESS: null,
  CONFIRM_ACTIVATION_FAILURE: null,
  START_CONFIRM_ACTIVATION: null,
  FINISH_CONFIRM_ACTIVATION: null,

  RESEND_ACTIVATION_EMAIL_REQUEST: null,
  RESEND_ACTIVATION_EMAIL_SUCCESS: null,
  RESEND_ACTIVATION_EMAIL_FAILURE: null,
  START_RESEND_ACTIVATION_EMAIL: null,
  FINISH_RESEND_ACTIVATION_EMAIL: null,

  SEND_RESET_PASSWORD_MAIL_REQUEST: null,
  SEND_RESET_PASSWORD_MAIL_SUCCESS: null,
  SEND_RESET_PASSWORD_MAIL_FAILURE: null,
  START_SEND_RESET_PASSWORD_MAIL: null,
  FINISH_SEND_RESET_PASSWORD_MAIL: null,

  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,
  START_RESET_PASSWORD: null,
  FINISH_RESET_PASSWORD: null,

  CLEAR_PROFILE: null,
}, 'PROFILE' );
