export const DELAY_DURATIONS = {
  GET_PROFILE: 10000,
  CREATE_PROFILE: 15000,
  DELETE_PROFILE: 10000,
  CONFIRM_ACTIVATION: 10000,
  RESEND_ACTIVATION_EMAIL: 15000,
};

const BASE = '/profile';

export const ENDPOINTS = {
  GET_PROFILE: BASE,
  CREATE_PROFILE: BASE,
  DELETE_PROFILE: BASE,
  CONFIRM_ACTIVATION: BASE + '/activate',
  RESEND_ACTIVATION_EMAIL: BASE + '/resend-activation',
  SEND_RESET_PASSWORD_MAIL: BASE + '/send-reset-password-mail',
  RESET_PASSWORD: BASE + '/reset-password',
};
