export default {
  HELVETICA_NEUE: 'Helvetica Neue',

  TINY_RELATIVE_SIZE: '0.25rem',
  SMALL_RELATIVE_SIZE: '0.5rem',
  EXTRA_SMALL_FONT_SIZE: '8px',
  SMALL_FONT_SIZE: '0.83rem',
  MEDIUM_FONT_SIZE: '1rem',
  MEDIUM_LARGE_FONT_SIZE: '1.1rem',
  LARGE_FONT_SIZE: '1.166rem',
  LARGE_GIANT_FONT_SIZE: '1.25rem',
  GIANT_FONT_SIZE: '1.5rem',
  EXTRA_GIANT_FONT_SIZE: '1.66rem',
  MASSIVE_RELATIVE_SIZE: '2.5rem',

};
