export default {
  PRIMARY_FONT: 'Avenir',
  AVENIR_BOOK_FONT: 'Avenir-Book',
  HELVETICA_NEUE: 'HelveticaNeue',

  EXTRA_SMALL_FONT_SIZE: '8px',
  SMALL_FONT_SIZE: '10px',
  MEDIUM_FONT_SIZE: '12px',
  MEDIUM_LARGE_FONT_SIZE: '14px',
  LARGE_FONT_SIZE: '17px',
  EXTRA_LARGE_FONT_SIZE: '20px',
  GIANT_FONT_SIZE: '32px',

};
